name = "claude-code-mcp-standalone"
main = "src/worker-standalone.ts"
compatibility_date = "2025-08-15"

# Account and zone IDs from .env.txt
account_id = "1d5ebf460e5ef491d9ca5f7c93c1fc24"

[vars]
# These can be overridden with wrangler secret put commands
ALLOWED_TOOLS = "Bash,Read,Git,Write,Edit,MultiEdit,Glob,Grep,LS"
DISALLOWED_TOOLS = ""

# Secrets (set via wrangler secret put ANTHROPIC_API_KEY)
# ANTHROPIC_API_KEY = "set-via-wrangler-secret"